/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaapplication17;


import javax.swing.*;

public class loginQrCode extends javax.swing.JFrame {

    /**
     * Creates new form loginQrCode
     */
    public loginQrCode() {
        initComponents();
        this.setSize(720, 364);
        setLocationRelativeTo(null);
        this.setTitle("BXB");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        name_adminTf = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        admin_codeTf = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        login = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);
        getContentPane().add(name_adminTf);
        name_adminTf.setBounds(287, 192, 223, 22);

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Name:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(187, 195, 37, 16);

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Admin Code:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(187, 234, 69, 16);

        admin_codeTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                admin_codeTfActionPerformed(evt);
            }
        });
        getContentPane().add(admin_codeTf);
        admin_codeTf.setBounds(287, 234, 223, 22);

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Course Code:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(187, 273, 70, 16);
        getContentPane().add(jTextField3);
        jTextField3.setBounds(287, 273, 223, 22);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("ADMIN");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(280, 100, 168, 64);

        login.setText("LOG IN");
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });
        getContentPane().add(login);
        login.setBounds(480, 330, 72, 23);

        jButton2.setText("SIGN-UP");
        getContentPane().add(jButton2);
        jButton2.setBounds(370, 330, 76, 23);

        jButton3.setText("BACK");
        getContentPane().add(jButton3);
        jButton3.setBounds(270, 330, 72, 23);

        jButton4.setText("EXIT");
        getContentPane().add(jButton4);
        jButton4.setBounds(160, 330, 72, 23);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication17/Artboard 5 copy.png"))); // NOI18N
        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 0, 720, 370);

        setSize(new java.awt.Dimension(734, 371));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void admin_codeTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_admin_codeTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_admin_codeTfActionPerformed

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
        // TODO add your handling code here:
        String adminName = name_adminTf.getText();
                String adminCode = admin_codeTf.getText();
                
                if (adminName.equals("Anaceito N. Mercado") && adminCode.equals("123")) {
                    NewJFrame3 vs = new NewJFrame3();
                    vs.setVisible(true);
                    dispose();
                } else if (adminName.equals("Kent Andrew Carandang") && adminCode.equals("132")) {
                   NewJFrame3 vs = new NewJFrame3();
                    vs.setVisible(true);
                    dispose();
                } else if (adminName.equals("Charlotte Diane Delmo") && adminCode.equals("312")) {
                   NewJFrame3 vs = new NewJFrame3();
                    vs.setVisible(true);
                    dispose();
                } else if (adminCode.equals("Philip Caguete") && adminName.equals("321")) {
                    NewJFrame3 vs = new NewJFrame3();
                    vs.setVisible(true);
                    dispose();
                } else {
                    JOptionPane.showMessageDialog(loginQrCode.this, "Invalid admin name or code",
                            "Login Error", JOptionPane.ERROR_MESSAGE);
                }    
    }//GEN-LAST:event_loginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(loginQrCode.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(loginQrCode.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(loginQrCode.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(loginQrCode.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new loginQrCode().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField admin_codeTf;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JButton login;
    private javax.swing.JTextField name_adminTf;
    // End of variables declaration//GEN-END:variables

    private void NewJFrame(String admin_1) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
