/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaapplication17;

/**
 *
 * @author Alysa Emilio
 */
public class OOP_QRCode extends javax.swing.JFrame {

    /**
     * Creates new form OOP_QRCode
     */
    public OOP_QRCode() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tracker = new javax.swing.JTable();
        saveDB = new javax.swing.JButton();
        showabsent = new javax.swing.JButton();
        passwordLabel6 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        scanner = new javax.swing.JPanel();
        SRcode = new javax.swing.JTextField();
        nametf = new javax.swing.JTextField();
        savetodb = new javax.swing.JButton();
        done = new javax.swing.JButton();
        date = new javax.swing.JLabel();
        time = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jLabel3.setFont(new java.awt.Font("Poppins ExtraLight", 2, 17)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("BS IN COMPUTER ENGINEERING (2ND YEAR)");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel6.setFont(new java.awt.Font("Bebas Neue", 0, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("STUDENT ATTENDANCE TRACKER");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(20, 10, 630, 47);

        jLabel4.setFont(new java.awt.Font("Poppins ExtraLight", 2, 17)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("BS IN COMPUTER ENGINEERING (2ND YEAR)");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 50, 363, 23);

        tracker.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "SR Code", "Date", " Time", "Attendance"
            }
        ));
        jScrollPane3.setViewportView(tracker);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(20, 100, 530, 200);

        saveDB.setBackground(new java.awt.Color(102, 102, 102));
        saveDB.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        saveDB.setForeground(new java.awt.Color(255, 255, 255));
        saveDB.setText("DB");
        saveDB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveDBActionPerformed(evt);
            }
        });
        getContentPane().add(saveDB);
        saveDB.setBounds(20, 320, 90, 23);

        showabsent.setBackground(new java.awt.Color(102, 102, 102));
        showabsent.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        showabsent.setForeground(new java.awt.Color(255, 255, 255));
        showabsent.setText("Show Absent/s");
        showabsent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showabsentActionPerformed(evt);
            }
        });
        getContentPane().add(showabsent);
        showabsent.setBounds(430, 320, 120, 23);

        passwordLabel6.setBackground(new java.awt.Color(255, 255, 255));
        passwordLabel6.setFont(new java.awt.Font("Proxima Nova Lt", 0, 18)); // NOI18N
        passwordLabel6.setForeground(new java.awt.Color(0, 0, 0));
        passwordLabel6.setText("Course:");
        getContentPane().add(passwordLabel6);
        passwordLabel6.setBounds(30, 370, 86, 24);

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField3);
        jTextField3.setBounds(140, 370, 230, 22);

        scanner.setBackground(new java.awt.Color(255, 255, 255));
        scanner.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(scanner);
        scanner.setBounds(580, 70, 250, 230);

        SRcode.setEditable(false);
        SRcode.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        SRcode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SRcodeActionPerformed(evt);
            }
        });
        getContentPane().add(SRcode);
        SRcode.setBounds(580, 330, 250, 30);

        nametf.setEditable(false);
        nametf.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nametf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nametfActionPerformed(evt);
            }
        });
        getContentPane().add(nametf);
        nametf.setBounds(580, 370, 250, 30);

        savetodb.setBackground(new java.awt.Color(102, 102, 102));
        savetodb.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        savetodb.setForeground(new java.awt.Color(255, 255, 255));
        savetodb.setText("Save to Database");
        savetodb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savetodbActionPerformed(evt);
            }
        });
        getContentPane().add(savetodb);
        savetodb.setBounds(310, 430, 130, 23);

        done.setBackground(new java.awt.Color(102, 102, 102));
        done.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        done.setForeground(new java.awt.Color(255, 255, 255));
        done.setText("Done");
        done.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doneActionPerformed(evt);
            }
        });
        getContentPane().add(done);
        done.setBounds(470, 430, 130, 23);

        date.setForeground(new java.awt.Color(0, 0, 0));
        date.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        date.setText("0");
        getContentPane().add(date);
        date.setBounds(580, 410, 250, 20);

        time.setBackground(new java.awt.Color(255, 255, 255));
        time.setForeground(new java.awt.Color(0, 0, 0));
        time.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        time.setText("0");
        getContentPane().add(time);
        time.setBounds(580, 430, 250, 20);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication17/Artboard 5 copy1.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-3, -4, 930, 490);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveDBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveDBActionPerformed
        // TODO add your handling code here:
        //        String namet = name.getText();
        //        String srcodet = srcode.getText();
        //        String datet = date.getText();
        //        String timet = time.getText();
        //        String attendance = "PRESENT";
        //
        //
        //        Object[] data = {namet, srcodet, datet, timet, attendance};

        DefaultTableModel tblModel = (DefaultTableModel)tracker.getModel();
        //        tblModel.addRow(data);

        if(tblModel.getRowCount()==0){
            JOptionPane.showMessageDialog(null, "Table is Empty");
        }

        else {
            try {
                String nm, src, dte, tm, att;
                Class.forName("com.mysql.jdbc.Driver");
                con = DriverManager.getConnection("jdbc:mysql://localhost/trackeradmin","root","");

                for (int i=0; i<tblModel.getRowCount(); i++){
                    nm = tblModel.getValueAt(i, 0).toString();
                    src = tblModel.getValueAt(i, 1).toString();
                    dte = tblModel.getValueAt(i, 2).toString();
                    tm = tblModel.getValueAt(i, 3).toString();
                    att = tblModel.getValueAt(i, 4).toString();
                    String query = "INSERT into `mercado_anacieto_oop`(`Name`, `SR Code`, `Date`, `Time`, `ATTENDANCE`) VALUES (?,?,?,?,?)";
                    PreparedStatement prepstmt = con.prepareStatement(query);
                    prepstmt.setString(1, nm);
                    prepstmt.setString(2, src);
                    prepstmt.setString(3, dte);
                    prepstmt.setString(4, tm);
                    prepstmt.setString(5, att);

                    prepstmt.execute();
                    tblModel.setRowCount(0);

                    JOptionPane.showMessageDialog(null, "Your information has been uploaded to the system.");

                }

            } catch (ClassNotFoundException ex) {
                Logger.getLogger(OOP_QRCodeScanner.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(OOP_QRCodeScanner.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

        SRcode.setText("");

    }//GEN-LAST:event_saveDBActionPerformed

    private void showabsentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showabsentActionPerformed

        try {
            // donee time out (SELECT `ATTENDANCE` FROM `mercado_anacieto_oop_display` WHERE `ATTENDANCE`= "ABSENT";)

            pst=con.prepareStatement("SELECT `SR Code`, `Name`, `TIME`, `ATTENDANCE` FROM `mercado_anacieto_oop_display` WHERE `ATTENDANCE`= \"ABSENT\"");
            rs = pst.executeQuery();
            DefaultTableModel model = (DefaultTableModel)tracker.getModel();
            model.setRowCount(0);

            while (rs.next()){
                model.addRow(new String[]{rs.getString(1), rs.getString(2), rs.getString(3), rs.getString(4)});
            }
        } catch (SQLException ex) {
            Logger.getLogger(OOP_QRCodeScanner.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_showabsentActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void SRcodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SRcodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SRcodeActionPerformed

    private void nametfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nametfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nametfActionPerformed

    private void savetodbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savetodbActionPerformed
        // TODO add your handling code here:
        //        att.setText("PRESENT");
        //        String attd = att.getText();
        //        String namet = name.getText();
        //        String srcodet = srcode.getText();
        //        String datet = date.getText();
        //        String timet = time.getText();
        //
        //
        //
        //        Object[] data = {namet, srcodet, datet, timet, attd};
        //
        //        DefaultTableModel tblModel = (DefaultTableModel)tracker.getModel();
        //        tblModel.addRow(data);

    }//GEN-LAST:event_savetodbActionPerformed

    private void doneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_doneActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OOP_QRCode.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OOP_QRCode.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OOP_QRCode.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OOP_QRCode.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OOP_QRCode().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField SRcode;
    private javax.swing.JLabel date;
    private javax.swing.JButton done;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField nametf;
    private javax.swing.JLabel passwordLabel6;
    private javax.swing.JButton saveDB;
    private javax.swing.JButton savetodb;
    private javax.swing.JPanel scanner;
    private javax.swing.JButton showabsent;
    private javax.swing.JLabel time;
    private javax.swing.JTable tracker;
    // End of variables declaration//GEN-END:variables
}
